# .pre-commit-config.yaml
repos:
- repo: local
  hooks:
    - id: extract-version
      name: Extract CLI version
      entry: python scripts/extract_version.py
      language: python
      types: [python]
      files: pyproject.toml
      additional_dependencies:
        - toml
